// Compiled using defi 1.0.0 (TypeScript 4.9.5)
var LetterInteger;
(function (LetterInteger) {
    LetterInteger[LetterInteger["A"] = 1] = "A";
    LetterInteger[LetterInteger["B"] = 2] = "B";
    LetterInteger[LetterInteger["C"] = 3] = "C";
    LetterInteger[LetterInteger["D"] = 4] = "D";
    LetterInteger[LetterInteger["E"] = 5] = "E";
    LetterInteger[LetterInteger["F"] = 6] = "F";
    LetterInteger[LetterInteger["G"] = 7] = "G";
    LetterInteger[LetterInteger["H"] = 8] = "H";
    LetterInteger[LetterInteger["I"] = 9] = "I";
    LetterInteger[LetterInteger["J"] = 10] = "J";
    LetterInteger[LetterInteger["K"] = 11] = "K";
    LetterInteger[LetterInteger["L"] = 12] = "L";
    LetterInteger[LetterInteger["M"] = 13] = "M";
    LetterInteger[LetterInteger["N"] = 14] = "N";
    LetterInteger[LetterInteger["O"] = 15] = "O";
    LetterInteger[LetterInteger["P"] = 16] = "P";
    LetterInteger[LetterInteger["Q"] = 17] = "Q";
    LetterInteger[LetterInteger["R"] = 18] = "R";
    LetterInteger[LetterInteger["S"] = 19] = "S";
    LetterInteger[LetterInteger["T"] = 20] = "T";
    LetterInteger[LetterInteger["U"] = 21] = "U";
    LetterInteger[LetterInteger["V"] = 22] = "V";
    LetterInteger[LetterInteger["W"] = 23] = "W";
    LetterInteger[LetterInteger["X"] = 24] = "X";
    LetterInteger[LetterInteger["Y"] = 25] = "Y";
    LetterInteger[LetterInteger["Z"] = 26] = "Z";
})(LetterInteger || (LetterInteger = {}));
